# Question 1

In [45]:
import numpy as np
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Question 2

In [46]:
arr1= np.arange(10,50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Question 3

In [47]:
mat1=np.arange(9).reshape(3,3)
print(mat1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Question 4

In [48]:
arr3=np.nonzero([1,2,0,0,4,0])
print(arr3)

(array([0, 1, 4], dtype=int64),)


# Question 5

In [56]:
arr4=np.random.randint((10,10))
a,b=arr4.min(),arr4.max()
print("minimum is",a,"maximum is",b)

minimum is 0 maximum is 5


# Question 6

In [62]:
vec=np.random.random(30)
# print(vec)
m=vec.mean()
print("mean is ",m)

mean is  0.49104206103576986
